End mode selection on "-obs" command from players[0]
island-troll-tribes/island-troll-tribes pull request #656
Opened 2020-11-24 00:24 UTC by Jaccouille

Ending the game mode selection when the player from the first slot type -obs, this way people don't have to wait when the player picking mode goes observer.

2020-11-24 02:57 UTC, jonathanmclaus commented
I think it would make more sense to delay the `obs` action until after mode selection ends. What do you think? Basically I think the changes from modes should be finalized once mode selection finishes.

2020-11-24 04:28 UTC, theQuazz commented
That will make troll selection a bit messier because then you might need to undo someone picking a troll. Also the enemy team might think they're playing against a different number of characters so choose a certain composition and then someone could obs at the last second, throwing off their plan. It was very intentional for me to only allow `-obs` during mode selection, which should be thought of as game initialization.

2020-11-24 04:29 UTC, theQuazz approved these changes

2020-11-24 06:43 UTC, jonathanmclaus requested changes
I think we should discuss how this should work.

2020-11-24 19:21 UTC, jonathanmclaus commented
@theQuazz I meant that `-obs` would only be allowed during mode selection, but that it would take effect when mode selection ended, preventing the host from accidentally changing to observer before finishing modes.

2020-11-24 19:22 UTC, theQuazz commented
@jonathanmclaus ah that makes sense

2020-11-24 19:25 UTC, jonathanmclaus commented
Right now it's slightly helpful to immediately become an observer because you see the update in the allies screen, but I thought at some point there was a plan to switch off the standard observer behavior for WC3, in which case that benefit doesn't apply.

2020-11-24 19:29 UTC, theQuazz commented
I tried but it wasn't successful. We can keep trying though if you want.

2020-11-24 19:45 UTC, jonathanmclaus commented
What was the problem? I don't remember if you tried before tribes were always a thing. I think we could just have a pool of players without a tribe, which have shared vision from all players, always a scoreboard, no troll, and are ignored for game ending conditions. The last 2 behaviors should happen naturally from not having a tribe.

2020-11-24 19:51 UTC, theQuazz commented
Try `-obs-new` in game

2020-12-21 05:26 UTC, jonathanmclaus commented
I think we should switch to new-style observers but this is a good workaround in the meanwhile.

2020-12-21 05:26 UTC, merged